language: objective-c
osx_image: xcode7
git:
  submodules: false
before_install:
  - brew update; brew update
  # - brew outdated xctool || brew upgrade xctool
  - brew install carthage
install: script/update
script: script/test
